#!/usr/bin/env bash
#
# Run verify* script before pushing to remote branch

set -euo pipefail

GIT_ROOT=$(git rev-parse --show-toplevel)

cd "${GIT_ROOT}" || exit 1

./verify/verify-boilerplate.sh
./verify/verify-dashboard-format.sh
./verify/verify-flags-underscore.py
./verify/verify-lint.sh
./verify/test.sh
